### ISSUE TITLE
Apple M1 Mac: `cobweb create site` does not work because of system's Git version string

### ISSUE THREAD

**Issue by tscholze** [varabyte/kobweb#147]
The command `kobweb create site` does not finish or even start asking the question to setup a new project.
Please see [Discord discussion](https://discord.com/channels/886036660767305799/886039480316858368/962407624345808997). 

If relevant, specify:
* OS:  Mac (M1)
* Kobweb CLI version: `kobweb 0.9.8`

---

It seems that the `GIT_VERSION_REGEX` pattern does not conform with the `git version` output on a Mac M1 which is `git version 2.32.0 (Apple Git-132)`. If I patch it (not commit-able), the wizard works as expected.

```
val process = Runtime.getRuntime().git("version")
        val versionDeferred = CompletableDeferred<GitVersion>()
        process.consumeProcessOutput { line, isError ->
            val result = GIT_VERSION_REGEX.matchEntire(line)
            if (result != null) {
                versionDeferred.complete(GitVersion(
                    result.groupValues[2].toInt(),
                    result.groupValues[3].toInt(),
                    result.groupValues[4].toInt(),
                ))
            } else {
                throw KobwebException("git must be installed and present on the path") // this gets triggered
            }
        }
```

**Comment by bitspittle** [comment]
Will be fixed in 0.9.9
