### ISSUE TITLE
Cannot build project with custom source sets name

### ISSUE THREAD

**Issue by DVDAndroid** [varabyte/kobweb#150]
In Kotlin Multiplatform is it possible to change the default source set name (like `js` or `jvm`) to a custom one

`build.gradle.kts`
```
kotlin {
    jvm("myBackend") {...}
    js("myFrontend", IR) {...}
    sourceSets {
        val myFrontendMain by getting {...}
        val myBackendMain by getting {...}
    }
}
```

When running `kobwebStart` the following error occurs:
`Task with name 'jsBrowserDevelopmentRun' not found in root project`

**Comment by bitspittle** [comment]
Thank you so much for filing and fixing the issue in a single stroke.

I hope my Gradle code wasn't too painful to navigate. I was learning a lot as I went along. If you saw anything else in there you thought could use any improvement, please don't hesitate to let me know.
