### ISSUE TITLE
Failed to install Kobweb with brew in MacOS Apple Silicon

### ISSUE THREAD

**Issue by jeluchu** [varabyte/kobweb#217]
Hi, I have tried to follow the steps correctly as indicated in the README documentation in order to install Kobweb, but for some reason I am not managing to install it. I show image below:

![Captura de Pantalla 2023-03-27 a las 10 22 43](https://user-images.githubusercontent.com/32357592/227884615-a9a0eb09-ee59-496c-ab5b-224b0e9bc20b.png)

I run the command brew install varabyte/tap/kobweb as indicated (I have brew installed), but for some reason when running the brew process it shows an error when performing git clone

If relevant, specify:
* OS: MacOS M1
* Kobweb libs version: Last version
* Kobweb CLI version: Last version

**Comment by bitspittle** [comment]
I am so sorry! I just saw this.

Can you install other things with homebrew? This looks like an error with the way things homebrew set things up, but I'm not sure.

I saw this answer on SO: https://stackoverflow.com/a/64350235

Can you try running

```bash
git config --global init.defaultBranch main
```
?

Does that help?

**Comment by bitspittle** [comment]
(Oh no! I have a filter that tries to catch "CI workflow failed" messages and it caught your message because it saw an email that came from GitHub with "Failed" in the subject. Sorry again about that)

**Comment by bitspittle** [comment]
I just randomly noticed this issue in my backlog. Since there was no reply for a while and I haven't had any one else bring up this issue, I'm going to close it. However, if you happen to see this and want to continue the conversation, you are welcome to ping this issue, especially if you're seeing it's still happening.
