### ISSUE TITLE
Kobweb build does not accept all JVM target ?

### ISSUE THREAD

**Issue by tessanix** [varabyte/kobweb#236]
I followed the [Stevdza-San](https://www.youtube.com/watch?v=F5B-CxJTKlg&t=1096s) guide to install and run Kobweb. But instead downloading JDK 11 I installed JDK 20. Then, when I used the command `kobweb run` I got this error : 

```
FAILURE: Build failed with an exception.                                                                   
                                                                                                           
* What went wrong:                                                                                         
Execution failed for task ':site:compileKotlinJvm'.                                                        
> Error while evaluating property 'compilerOptions.jvmTarget' of task ':site:compileKotlinJvm'.            
   > Failed to calculate the value of property 'jvmTarget'.                                                
      > Unknown Kotlin JVM target: 20
```
Thanksfully, just by adding this line of code `jvm { jvmToolchain(18) }` in the build.gradle.kts (:site) file I had been able to run correctly the project and launch the server. Why 18 and not 20 ? I don't know. I have multiple version of Java that my intelliJ IDEA is using, that could be a reason. 

* OS: Windows 11
* Kobweb libs version: 0.13.1
* Kobweb CLI version: 0.9.12

**Comment by bitspittle** [comment]
This is almost certainly not a Kobweb issue. In other words, I'm pretty sure there isn't anything I can do.

https://github.com/gradle/gradle/issues/23488 makes it sound like JDK 20 is too new both for Gradle 8.1 (the latest version) *and* Kotlin 1.8.20. You have run up to the bleeding edge and then dashed passed it!

By setting a jvmToolchain, you're probably instructing Gradle to auto-download JDK 18 for you behind your back without realizing it. Which is fine! But you can also instead manually install JDK 18 (or 11).

Whenever newer versions of Kotlin and gradle come out, I'll be keeping Kobweb and its templates up to date.

**Comment by tessanix** [comment]
Thank you for the answer. I appreciate this explanation too, I think I have nothing more to say.
