### ISSUE TITLE
Consider refactoring the "notify..." methods in the Kobweb Gradle Application plugin

### ISSUE THREAD

**Issue by bitspittle** [varabyte/kobweb#238]
The Kobweb Application plugin currently has a few global "notify" methods which, if called, help Kobweb set up dependencies so that tasks are ordered correctly after being informed about custom user actions. 

Sepcifically: 

* `notifyKobwebAboutFrontendCodeGeneratingTask(...)`
* `notifyKobwebAboutBackendCodeGeneratingTask(...)`
* `notifyKobwebAboutServerPluginTask(...)`

Here, I create some files on my blogging site and then tell Kobweb, "HEY, I MADE THESE, you might want to make sure you compile them": https://github.com/bitspittle/bitspittle.dev/blob/222310af50d8f17973d733ee9dfee0d49aceb421/site/build.gradle.kts#L190

However, before 1.0, we should...

* Consider if this is the right way you are supposed to do things in Gradle
* Maybe move these methods into a non-global method scope? For example:

```
kobweb {
   app {
      addFrontendCodeGeneratingTask(...)
   }
   server {
      addBackendCodeGeneratingTask(...)
      addServerPluginTask(...)
   }
}
```

**Comment by DennisTsar** [comment]
We figured out the right way to do this in Gradle and the `notify...` methods are now deprecated.
- [Guide for code generation](https://github.com/varabyte/kobweb?tab=readme-ov-file#generating-site-code-at-compile-time)
- [Guide for server plugins](https://github.com/varabyte/kobweb?tab=readme-ov-file#register-your-server-plugin-jar)
