### ISSUE TITLE
I believe that this project will participate in the JB financial support program.

### ISSUE THREAD

**Issue by victorYghor** [varabyte/kobweb#240]
This is the application link : https://docs.google.com/forms/d/e/1FAIpQLSfihYy9ot3RPmiaMrEVmE_xgJlGnYg8zXewnF1-r2YXqi3CKg/viewform
https://www.youtube.com/@Kotlin/community

**Comment by bitspittle** [comment]
Thank you for making sure I knew about this! I actually applied thanks to people on my Discord server pointing it out when it became available. Otherwise, I would have missed it for sure.

If you use Discord, feel free to join us there! (Link is at the top of the README if you're interested)
