### ISSUE TITLE
EPIC: IJ Kobweb Plugin

### ISSUE THREAD

**Issue by bitspittle** [varabyte/kobweb#252]
Some initial ideas:

* CSS to Kobweb (see also: https://opletter.github.io/css2kobweb/)
* Refactor inline styles into component style
* Actions to quickly create component styles
* Custom warnings (like if ComponentStyle is missing `base`)
* Wraps Modifier chain that is two modifiers or longer, into one modifier per line. (Exists in AS)
* Show colors in the bumper for Kobweb `Colors` class.
* Warn if user is returning Modifier directly in a component style or variant without `base` (and offer assistance to convert the style or variant to using the `base` API)
* Warn if a user is using an attribute modifer within a component style (and offer assistance to extract it to the `extraModifiers` parameter)
* Warn if the Kobweb version is being paired with the wrong Compose library (detect in libs.versions.toml directly but also can we check the final model built by Gradle in case someone isn't using libs.versions.toml?)
* Make sure StyleVariables declare themselves using CSSLengthNumericValue not CSSLengthValue
* Warn if people are using a Compose HTML version of some API when the Kobweb version is better (e.g. animation stuff?)
* Warn if remembering a worker without using `rememberWorker`
* Easy linking to mozilla docs, e.g. when looking at quick docs for Kobweb modifiers

**Comment by bitspittle** [comment]
From a user on my Discord:

> There is this one existing IJ plugin i found useful when working with Kobweb. It will be nice to be able to convert html into Kobweb too.
https://plugins.jetbrains.com/plugin/12205-html-to-kotlinx-html

**Comment by charlee-dev** [comment]
Another one that would be useful is a preview tab in IJ with different screen resolutions and hot reload.

**Comment by charlee-dev** [comment]
Another is a Sidebar with pre-made Kobweb components (similar to the view picker in Xcode combined with the customizability of Android ones):
- with component preview
- with the possibility to customise properties
- a button that will add component code where the cursor currently is.

**Comment by bitspittle** [comment]
The issues here have been broken up and moved to https://github.com/varabyte/kobweb-intellij-plugin
