### ISSUE TITLE
Plugin [id: 'com.varabyte.kobweb.application', version: '0.13.7'] was not found 

### ISSUE THREAD

**Issue by jifffffy** [varabyte/kobweb#266]
kobweb gradle plugin not found!

---
this plugin is not found in https://us-central1-maven.pkg.dev/varabyte-repos/public, is the repo exist?  I got a 404 error.

**Comment by bitspittle** [comment]
Make sure your project includes the maven repository where Kobweb plugins
live. (See step 4 here:
https://github.com/varabyte/kobweb#adding-kobweb-to-an-existing-project)

Alternately, in a temporary directory, run:

```
$ kobweb create app
$ cd app/site
$ kobweb run
```

If that works, it means your computer can access the Kobweb gradle plugin.
In that case, check that project compared to your own (especially
settings.gradle.kts and build.gradle.kts files) to see what's different.

Good luck!

**Comment by jifffffy** [comment]
Im sorry. I find the problem is VPN. I set the http proxy in the idea. the problem has gone.

**Comment by bitspittle** [comment]
Thanks for the update. Good luck with the project!
