### ISSUE TITLE
[Question] How to read xlsx format file? And pass it to JSON?

### ISSUE THREAD

**Issue by mrenann** [varabyte/kobweb#328]
How to read xlsx format file? And pass it to JSON?
After reading and arriving in Bytearray format I cannot proceed to JSON

When I receive a file, I would like to save it in the database

**Comment by bitspittle** [comment]
I'm afraid there's a lot of context I don't have here.

My best recommendation would be to look at `kobweb create examples/todo` and see how it's using Kotlin serialization to communicate between frontend and backend. As for reading xlsx, that's out of scope of Kobweb, so I don't really know. But a quick Google search shows a library that might be worth trying: https://github.com/timo-drick/kotlin_xlsx_serializer

**Comment by bitspittle** [comment]
Since this question is not directly Kobweb related, and because our resources are currently very limited, I'm going to close this issue. However, you can reply if you have specific questions about Kobweb, thanks for understanding!
