### ISSUE TITLE
Kobweb CLI 0.9.13 unable to fetch templates

### ISSUE THREAD

**Issue by erictoader** [varabyte/kobweb#361]
Running `kobweb create` or `kobweb list` fails to clone the templates repository, thus making it impossible to create a project. 
I also ran this command on CLI 0.9.11 and it worked with no issues.

* OS: MacOS Sonoma
* Kobweb CLI version: 0.9.13

**Comment by bitspittle** [comment]
Wow, I haven't heard anything about this before. Can you share any more details about how it failed? It's been a long time since 0.9.13 went out, but I can try to check to see what changed between 0.9.11. What about 0.9.12 for you? And how did you get the old version, did you build from source?

**Comment by erictoader** [comment]
0.9.13 is the newest version of the CLI i believe. I installed it via `brew install kobweb`.
To get the older version, I just downloaded the binaries and then added it to path. Seems to work fine and is compatible with the latest version of everything.

The message was that it was trying to clone the templates, succeding, but saying that no templates were found.

**Comment by bitspittle** [comment]
Yeah, I'm not sure. If Mac was totally broken, I expect I would have heard something by now.

Can you tell me exactly the commands you typed into kobweb?

Also, if you're up for it, could you try building from source?

```bash
$ git clone https://github.com/varabyte/kobweb-cli
$ cd kobweb-cli
$ ./gradlew :kobweb:installShadowDist
# Binary now lives at `/path/to/kobweb-cli/kobweb/build/install/kobweb/bin/kobweb`
```
If you run that and it fails, maybe we can debug what's going on?

**Comment by bitspittle** [comment]
Closing this issue due to lack of response. If OP sees this in the future, feel free to check the state of the issue and respond if it's still a problem for you.
