### ISSUE TITLE
cant get kobweb-core-0.15.0.pom from repo (maven and google)

### ISSUE THREAD

**Issue by AbolfazlNarimani** [varabyte/kobweb#378]
* OS:win11
* Kobweb libs version: kobweb = "0.15.0"
* Kobweb CLI version: 0.9.13

---

i have just created a project using cmd command "kobweb create" 
and libs wont download 
when i click on the links i get 404 error i have tested other maven (google as well) libs and they download fine
IntelliJ IDEA version is :
 IntelliJ IDEA 2023.2.5 (Community Edition)
Build #IC-232.10227.8, built on November 9, 2023
Runtime version: 17.0.9+7-b1000.46 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 11.0
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 20
Registry:
    debugger.new.tool.window.layout=true
    ide.experimental.ui=true

Non-Bundled Plugins:
    com.jetbrains.edu (2023.10-2023.2-955)
    org.jetbrains.kotlin (232-1.9.20-release-507-IJ10072.27)
    com.github.evgenys91.machinet (2022.1.54)
    com.squareup.sqldelight (2.0.0)
    com.sqlandroid (0.1.48)

Kotlin: 232-1.9
.20-release-507-IJ10072.27

here is the log : 

Could not resolve all dependencies for configuration ':site:jsCompileClasspath'.
> Could not find com.varabyte.kobweb:kobweb-core:0.15.0.
  Searched in the following locations:
    - https://repo.maven.apache.org/maven2/com/varabyte/kobweb/kobweb-core/0.15.0/kobweb-core-0.15.0.pom
    - https://dl.google.com/dl/android/maven2/com/varabyte/kobweb/kobweb-core/0.15.0/kobweb-core-0.15.0.pom
  Required by:
      project :site
> Could not find com.varabyte.kobweb:kobweb-silk:0.15.0.
  Searched in the following locations:
    - https://repo.maven.apache.org/maven2/com/varabyte/kobweb/kobweb-silk/0.15.0/kobweb-silk-0.15.0.pom
    - https://dl.google.com/dl/android/maven2/com/varabyte/kobweb/kobweb-silk/0.15.0/kobweb-silk-0.15.0.pom
  Required by:
      project :site
> Could not find com.varabyte.kobwebx:silk-icons-fa:0.15.0.
  Searched in the following locations:
    - https://repo.maven.apache.org/maven2/com/varabyte/kobwebx/silk-icons-fa/0.15.0/silk-icons-fa-0.15.0.pom
    - https://dl.google.com/dl/android/maven2/com/varabyte/kobwebx/silk-icons-fa/0.15.0/silk-icons-fa-0.15.0.pom
  Required by:
      project :site
> Could not find com.varabyte.kobwebx:kobwebx-markdown:0.15.0.
  Searched in the following locations:
    - https://repo.maven.apache.org/maven2/com/varabyte/kobwebx/kobwebx-markdown/0.15.0/kobwebx-markdown-0.15.0.pom
    - https://dl.google.com/dl/android/maven2/com/varabyte/kobwebx/kobwebx-markdown/0.15.0/kobwebx-markdown-0.15.0.pom
  Required by:
      project :site

Possible solution:
 - Declare repository providing the artifact, see the documentation at https://docs.gradle.org/current/userguide/declaring_repositories.html`

and my build.gradle files are all red and unsolved reference
![Screenshot (8)](https://github.com/varabyte/kobweb/assets/126610933/a219e012-92a8-49db-92f2-3c291801f2ea)
![Screenshot (9)](https://github.com/varabyte/kobweb/assets/126610933/53208183-7bb3-44c6-8b0b-8c541e5b0bd3)
![Screenshot (10)](https://github.com/varabyte/kobweb/assets/126610933/05b0fe10-7658-4ae1-930d-93dba69af433)

**Comment by bitspittle** [comment]
Thanks for the report!

Do you have some setting on your machine that blocks non-standard maven repos? Some companies use a firewall for example.

Because the `maven("https://us-centra1-maven.pkg.dev/varabyte-repos/public")` line declares the repository that Gradle should be using to download those repositories, but it's clearly not being checked in your error output.

**Comment by AbolfazlNarimani** [comment]
@bitspittle i only use windows defender and windows firewall and gave full access to files and internet 
I've restarted and deleted the cache a few times and nothing.
changed the ide version to previous one and gradle recognize the syntax now.
server is working with few warnings .

`warning workspace-aggregator-84063d9a-a446-4e77-b460-b0492444bc0a > abe > webpack-dev-server > webpack-dev-middleware > memfs@3.6.0: this will be v4
warning Ignored scripts due to flag.

1: file:///E:/Coco/Coco/site/src/jsMain/kotlin/com/abe/AppEntry.kt:16:14 Parameter 'ctx' is never used 
`

**Comment by bitspittle** [comment]
Ah great! Yep you're up and running.

The first warning comes from NPM, nothing much I can do about it in Kobweb I think.

The second warning is actually something I've been meaning to remove from the empty template. Thanks for the reminder!
