### ISSUE TITLE
Links with fragments don't work in markdown

### ISSUE THREAD

**Issue by bitspittle** [varabyte/kobweb#422]
Concrete example from the Discord....

 https://comsci.co.uk/100PcVatFreeBridge#Fundraising <-- goes to a subsection on the page

https://comsci.co.uk/opensource then scroll down to "Back" which links to ` /100PcVatFreeBridge#Fundraising`, which goes back to the page but does NOT scroll down.

This might be an issue with the browser loading the page too fast (instantly) and then the section isn't ready when "#" is visited. It might also just be a logic issue in Kobweb, see also: https://github.com/varabyte/kobweb/blob/ca0ccea5a257538bc8dc5dde5f74a0caa74654fc/frontend/kobweb-core/src/jsMain/kotlin/com/varabyte/kobweb/navigation/Router.kt#L322

^ Maybe I just need to fire that on a timer instead of instantly?

**Comment by kjeller** [comment]
I can not recreate this bug on 121.0.1 (64-bit) Firefox on Windows it seems. Back takes me to Fundraising with a scroll down

**Comment by bitspittle** [comment]
Fixed in 0.15.4

**Comment by bitspittle** [comment]
> I can not recreate this bug on 121.0.1 (64-bit) Firefox on Windows it seems. Back takes me to Fundraising with a scroll down.

Yeah I believe the author of the site fixed it when the new version of Kobweb was made available to them.
