### ISSUE TITLE
Inline code markdown links disappear

### ISSUE THREAD

**Issue by Treetrain1** [varabyte/kobweb#472]
Using the kobweb app template, the following markdown link does not render.
```
[`text`](https://github.com)
```
If I remove the code modifier from text, the hyperlink is able to display.

Here is an example:

Source file:
```
This is an example of the bug I’m reporting on [`GitHub`](https://github.com).
```

Text displayed on the website:
```
This is an example of the bug I’m reporting on .
```

Expected behavior would be something similar to [`this`](https://github.com)

OS: Linux
Kobweb libs version: 0.16.2
Kobweb CLI version: 0.9.15

**Comment by bitspittle** [comment]
Fascinating. I can reproduce. Thanks for the report! I'll try to take a look at it shortly, in case it's trivial to fix.

**Comment by bitspittle** [comment]
Actually, Compose 1.6.0 just got released, which is causing me to drop everything and push stuff out early. So probably this fix will be in later today, if nothing goes wrong with the release.
