### ISSUE TITLE
Add TOC to the README

### ISSUE THREAD

**Issue by okarmazin** [varabyte/kobweb#475]
Hello, could we get a Table of Contents at the top of the README file? I think it would help tremendously with navigation. IDEA can generate TOC for Markdown documents automatically.

---

(Optional) The relevant location:

- [x] README

**Comment by bitspittle** [comment]
Actually, GitHub does this for you automatically. Search for the button that looks like of like a hamburger button. It doesn't make sense to include my own TOC which is manual and error prone when they do it already.

The docs will eventually move to https://kobweb.varabyte.com/docs which will be even better, that's planned "soon".

**Comment by bitspittle** [comment]
See also: https://github.blog/changelog/2021-04-13-table-of-contents-support-in-markdown-files/

**Comment by okarmazin** [comment]
TIL. I had no idea GitHub had this feature. I would never have guessed that little icon was TOC. Thanks!

**Comment by bitspittle** [comment]
I didn't know either until I worked on Kobweb! But yeah once you notice it, it's super useful.

That said, Kobweb is definitely pushing it with respect to an approachable readme. So I hope it comes across that I agree with your general sentiment.
