### ISSUE TITLE
Typography (i.e. how to set fancy fonts)

### ISSUE THREAD

**Issue by bitspittle** [varabyte/kobweb#49]
We should look at how Jetpack Compose does it with Material theming and also Chakra UI?

**Comment by alialbaali** [comment]
Is there any way to set a regular .ttf font via Kobweb?

**Comment by bitspittle** [comment]
Apologies! But I don't have the bandwidth to respond to general questions on the issue tracker, I'm pretty overwhelmed at the moment.

However, if you have Discord, I'd highly recommend visiting our server (linked in the README), as you can search its history and get answers from our community. 

This can be done and I'm pretty sure this topic came up in our discord in the past.

Otherwise, the best high level advice I can give is to figure out how to do this in normal html / css, then use the `kobweb` block in the build script to set things that would normally appear in the `head` block of your sure, and then use an `InitSilk` block to register styles like I do [in my blog site](https://github.com/bitspittle/bitspittle.dev/blob/222310af50d8f17973d733ee9dfee0d49aceb421/site/src/jsMain/kotlin/dev/bitspittle/site/AppStyles.kt#L39).

I will be working on docs soon and have made a note to answer this question there when I get to it.
