### ISSUE TITLE
Export static layout success but no file generated

### ISSUE THREAD

**Issue by adityatri** [varabyte/kobweb#545]
OS: Mac
Kobweb libs version: 0.18.0
Kobweb CLI version: 0.9.15

---

I have run `kobweb export --layout static` and it's already got success with below message:
> BUILD SUCCESSFUL in 20s
> 36 actionable tasks: 9 executed, 27 up-to-date
> $ gradlew kobwebStop --stacktrace
> > Task :site:kobwebStop
> A Kobweb server running at http://localhost:8080 (PID = 1749) was stopped
> Deprecated Gradle features were used in this build, making it incompatible with Gradle 9.0.
> You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.
> For more on this, please refer to https://docs.gradle.org/8.7/userguide/command_line_interface.html#sec:command_line_warnings in the Gradle documentation.
> BUILD SUCCESSFUL in 1s
> 1 actionable task: 1 executed
> Export finished successfully

The issue is I can't find this exported files anywhere. Also I checked on Git and there are no new files being generated.
Can someone assist me on this?

Tested using this public repo and getting same issue..
https://github.com/binayshaw7777/Kotfolio

**Comment by adityatri** [comment]
Oops sorry my bad, just realized that the generated files will be under a hidden folder:
`/site/.kobweb/site`

Closing this as it's not an issue.

**Comment by bitspittle** [comment]
Been way too busy here preparing for a talk. Sorry I never responded to this!

**Comment by adityatri** [comment]
No worries man!
