### ISSUE TITLE
Allow users to define additional scripts

### ISSUE THREAD

**Issue by dhcoder** [varabyte/kobweb#55]
Right now, we generate an index.html but there's no way to influence which additionally scripts are included in there. We need a way to fix that, e.g. so we can depend on some existing JS library.

**Comment by bitspittle** [comment]
This should be possible now that we have the @InitKobweb annotation. Something like `ctx.scripts.add(...)`

**Comment by bitspittle** [comment]
Duplicate of #7 essentially
