### ISSUE TITLE
Incorrect "No pages were defined" error when adding then deleting a file.

### ISSUE THREAD

**Issue by bitspittle** [varabyte/kobweb#586]
(Thanks LoP for the repro steps!)

* Clone Kobweb: `git clone https://github.com/varabyte/kobweb`
* Create an empty kt file in `playground/sitelib/src/jvmMain/kotlin/playground`, e.g. `DeleteMe.kt`
* `./gradlew sitelib:clean`
* `./gradlew sitelib:kspKotlinJvm`
* Check that the generated `backend.json` contains data
* Delete the file you created in step 1
* `./gradlew sitelib:kspKotlinJvm`
* See that the generated `backend.json` contains no data

In the second ksp run, ksp correctly identifies that the deleted file is not relevant to our processor, but this it still runs our processor, giving it 0 files. Since we were given 0 files, we write out an empty data file. Later code consumes that file, which issues the "No pages were defined" warning (since the data file, well, lists no pages in it!)

This seems either to be a bug with KSP or a user error on our end due to a misunderstanding about it.

**Comment by bitspittle** [comment]
Issue confirmed on KSP side and will be fixed in 2.1

https://github.com/google/ksp/issues/2027

We'll close this issue after we can update Kobweb to use that release

**Comment by DennisTsar** [comment]
Fixed in 0.19.1, as KSP 2.0.20-1.0.25 contains the fix.
