### ISSUE TITLE
Router doesn't recognise routes having query parameter(s) without a trailing slash

### ISSUE THREAD

**Issue by shubhamsinghshubham777** [varabyte/kobweb#636]
This ticket is made in continuation to our conversation here: https://github.com/varabyte/kobweb/issues/588#issuecomment-2561968024

As mentioned [here](https://github.com/varabyte/kobweb/issues/588#issuecomment-2561966547), just like the client side navigation logic will try to add a slash if `/example-route` isn't found but `/example-route/` is, I'd expect the same behaviour from the router when dealing with routes having `query parameters`.

The simplest reproducer of this issue is:
1. Create a file named `Index.kt` inside `your_package.pages.results` package
2. Create a composable annotated with `@Page`
3. Once done, try to run this URL from your browser:
    ```
    http://localhost:8080/results/?search_query=test
    ```
4. The router should be able to find and display your page
5. Then try to run this from your browser:
    ```
    http://localhost:8080/results?search_query=test
    ```
6. Observe that the router is not able to find this URL.

**Comment by bitspittle** [comment]
Set `kobweb` to `0.20.1-SNAPSHOT` in your `libs.versions.toml` file and see if the behavior matches what you expect.

[Assuming it works, here's the commit, if you're curious!](https://github.com/varabyte/kobweb/commit/6c2c403f354f6e9347fba4a125043154b1b92346)

**Comment by shubhamsinghshubham777** [comment]
Yes it works as expected 🙌🏻 Thank you. We can close this ticket now.

**Comment by shubhamsinghshubham777** [comment]
> Set `kobweb` to `0.20.1-SNAPSHOT` in your `libs.versions.toml` file and see if the behavior matches what you expect.
> 
> [Assuming it works, here's the commit, if you're curious!](https://github.com/varabyte/kobweb/commit/6c2c403f354f6e9347fba4a125043154b1b92346)


Yes it works as expected 🙌🏻 Thank you. We can close this ticket now.
