### ISSUE TITLE
Allow projects to use Silk w/o Kobweb

### ISSUE THREAD

**Issue by bitspittle** [varabyte/kobweb#64]
Right now, Silk technically requires Kobweb as a dependency because...

* `SilkApp` delegates to `KobwebApp` (see SilkApp.kt)
* `Link` delegates to `KobwebLink` (see the Link.kt that is in the silk module)
* The Kobweb gradle plugin generates code that sets the `initSilkHook` method, which is where user component style configurations would be registered

There may be demand in the future to just use the Silk widgets without the rest of Kobweb, so this bug tracks this request. Especially, as the widget set grows, people might want to use some of them in their own non-Kobweb project, and having Silk be separate could possibly encourage a larger pool of devs to use it and contribute to it. And if Silk gets better, Kobweb gets better too.

---

It's quite possible all we need is...

* refactor the initialization logic out of SilkApp (the part currently in the `remember` block) into a public method that users can use
* refactor `Link` so there's a version that doesn't delegate to `KobwebLink`
* Document the `initSilkHook` method so users can set it themselves.

---

I am marking this bug as being required for the 1.0 milestone, since it's possible it may cause us to rethink the API before considering it final; but it's just a call for investigation. It's possible we will look into this and realize it's not urgent and can wait until a post-1.0 release.

**Comment by NorbertSandor** [comment]
`initSilkHook` seems to be gone in the latest version...

**Comment by bitspittle** [comment]
@NorbertSandor The exact code around this has changed but you should be able to review the latest README for instructions.

https://github.com/varabyte/kobweb/tree/main/frontend/silk-widgets
