### ISSUE TITLE
Update Kobweb to Kotlin 1.6.10

### ISSUE THREAD

**Issue by bitspittle** [varabyte/kobweb#80]
1.6.10 came out today (but we need to wait for Compose artifacts to catch up before we can upgrade)

**Comment by Xaseron** [comment]
https://github.com/JetBrains/compose-jb/releases/tag/v1.0.1 should be compatible with Kotlin 1.6.x

**Comment by bitspittle** [comment]
Thanks! I'll give that a shot today if I have time. :crossed_fingers:

**Comment by bitspittle** [comment]
Hmmm. With compose 1.0.1 and Kotlin 1.6.10, I'm getting:

```
e: This version (1.1.0-alpha06) of the Compose Compiler requires Kotlin version 1.5.31 but you appear to be using Kotlin version 1.6.10 which is not known to be compatible.  Please fix your configuration (or `suppressKotlinVersionCompatibilityCheck` but don't say I didn't warn you!).                                                   
```

I always hate this particular warning because I'm never quite sure where the coompose compiler version is coming from. I'm guessing it's coming from the kotlin multiplatform plugin, but that's being set to 1.6.10, which is the latest at the time.

---

If you're curious to try this yourself, maybe double check I'm not missing a version upgrade, you can...

1. clone kobweb
2. edit `gradle/libs.versions.toml`, updating any relevant versions
3. Go into `kobweb/examples/helloworld` and run `/.gradlew compileKotlinJs`

**Comment by bitspittle** [comment]
The error I was getting with my earlier comment was user error - I had a nested subproject which had its own dependency versions, so I had Kotlin 1.6.10 as the version of my multiplatform plugin in one place and 1.5.31 elsewhere.

With latest, everything looks like it's compiling smoothly!
