### ISSUE TITLE
Multiple refreshes, then blank page - no 404

### ISSUE THREAD

**Issue by PXNX** [varabyte/kobweb#87]
When loading a url such as `http://localhost:8080/test-refresh` - which does not exist in a given project - the page continuously refreshes for some time, after which a blank page appears.

Shouldn't this instead lead to a 404 status page immediately?

**Comment by PXNX** [comment]
Might be a bug aswell, seemed more like an improvement to me though ;)

**Comment by PXNX** [comment]
It seemingly refreshes forever in most cases.

**Comment by bitspittle** [comment]
Yes, invalid pages should 404!

**Comment by bitspittle** [comment]
I'll go ahead and and change this to a "bug" label, since I am pretty sure this was working at one point but broke at some point. But otherwise yeah it would have been an enhancement :)

Labels don't really matter too much at this point, since it's not too hard to manage all the open issues at this point.

**Comment by bitspittle** [comment]
I am able to reproduce this, thanks for filing. I think at some point I updated the "automatically reload when a page is recompiled" logic and must have broke this - it's getting confused and trying to reload repeatedly.

**Comment by bitspittle** [comment]
Hahaha it's not at all what I expected. I have a bad regex right now for parsing the URL, and your hyphen is confusing my (bad) code.

If you type `http://localhost:8080/testrefresh` it should behave correctly.

I will fix my URL parsing logic to be more correct. I should probably delegate to the [URL](https://developer.mozilla.org/en-US/docs/Web/API/URL) class if I can and not try to reinvent the wheel.

**Comment by bitspittle** [comment]
Will be fixed in kobweb 0.7.11

**Comment by PXNX** [comment]
> Hahaha it's not at all what I expected. I have a bad regex right now for parsing the URL, and your hyphen is confusing my (bad) code.
> 
> If you type `http://localhost:8080/testrefresh` it should behave correctly.
> 
> I will fix my URL parsing logic to be more correct. I should probably delegate to the [URL](https://developer.mozilla.org/en-US/docs/Web/API/URL) class if I can and not try to reinvent the wheel.

Regex is wonderful😅
