### ISSUE TITLE
kobwebStart -t not available via run config

### ISSUE THREAD

**Issue by gabe97330** [varabyte/kobweb#91]
README describes invocation of dev server with live loading via kobweb cli, gradle cli and intellij run config. I couldn't get the run config to work, see [youtrack issue](https://youtrack.jetbrains.com/issue/IDEA-284935).

Is there an alternative way to get the live loading to work via run config?

**Comment by bitspittle** [comment]
It used to work a few months ago. Autocomplete didn't work but it still
accepted it. Is the youtrack bug implying this broke recently?

If you need a workaround, would creating a shell script run config work?
https://www.jetbrains.com/help/idea/shell-scripts.html

Thanks for the heads up. I'll try this out myself today and update the
README. Although my assumption is they'll fix the big soon hopefully.

**Comment by bitspittle** [comment]
I added some workaround instructions to the README. I'll leave this bug open and will clean up the README later after IJ fixes their issue upstream.

**Comment by gabe97330** [comment]
will look into the shell script approach and will try focusing on cli (kobweb as well as gradlew) rather than run/config. Have more general questions on dev/test/debug workflow trade-offs which I'll attempt to articulate separately.

**Comment by bitspittle** [comment]
> Have more general questions on dev/test/debug workflow trade-offs...

Honestly, this is a huge weak point in Kobweb at the moment. I just haven't had much time to dwell on it. I've filed bug #93 for now to make sure I'm keeping track of this now as a 1.0 blocker. Please feel free to have discussion in that bug or in our Discord, whatever you prefer.

**Comment by bitspittle** [comment]
This was probably fixed by IJ a while ago, but confirmed in IntelliJ IDEA 2022.2.2 at least that this is working.
